version: '3'
services:
  login:
    container_name: webapp
    image: webapp
    restart: always
    build: .
    ports:
      - '8000:8000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
